#![forbid(unsafe_code)]

use cairn_core::{CairnError, Result};
use cairn_sigma::codec;
use std::path::Path;

/// Provenance metadata for a fetched rule set (ADR-0003).
#[derive(Debug, Clone)]
pub struct Provenance {
    pub pin: String,
    pub source: String,
    pub fetched_at: String, // UTC RFC3339
}

impl Provenance {
    /// Create a new Provenance record with the current UTC timestamp.
    pub fn new(pin: String, source: String) -> Self {
        let fetched_at = chrono::Utc::now().to_rfc3339();
        Self {
            pin,
            source,
            fetched_at,
        }
    }

    /// Format provenance as the PROVENANCE file content (matching fetch-and-encode.sh).
    pub fn to_file_content(&self) -> String {
        format!(
            "# Bundled Sigma ruleset provenance (ADR-0003).\n\
             # Regenerated by cairn-updater. The `pin` is the upstream SigmaHQ commit\n\
             # this XOR-encoded bundle was fetched from; it becomes the <commit-sha> half of\n\
             # the manifest's sigma_ruleset_ver = \"<commit-sha>+<aggregate-sha256>\".\n\
             pin = {}\n\
             source = {}\n\
             fetched_at = {}\n",
            self.pin, self.source, self.fetched_at
        )
    }
}

/// Write a single fetched, un-encoded rule to the output directory with XOR encoding.
///
/// Steps:
/// 1. XOR-encode the rule bytes (using cairn-sigma::codec::xor).
/// 2. Create the target rule's parent directory if needed.
/// 3. Write encoded bytes to `rules_dir/<rule_path>`.
///
/// Safety: This function does NOT follow symlinks or write outside `rules_dir`.
/// The path is canonicalized first to prevent directory traversal (threat-model #3).
pub fn write_encoded_rule_to_dir(
    rules_dir: &Path,
    rule_bytes: &[u8],
    rule_path: &str,
) -> Result<()> {
    // Reject absolute paths and any `..` / prefix / root components before joining.
    // This blocks lexical traversal before we ever touch the filesystem.
    let rel = Path::new(rule_path);
    if rel.is_absolute()
        || rel.components().any(|c| {
            matches!(
                c,
                std::path::Component::ParentDir
                    | std::path::Component::Prefix(_)
                    | std::path::Component::RootDir
            )
        })
    {
        return Err(CairnError::Other(format!(
            "unsafe rule path (absolute or contains '..'): {rule_path}"
        )));
    }

    // Canonicalize the rules output directory to prevent symlink traversal.
    let rules_dir = rules_dir
        .canonicalize()
        .map_err(|e| CairnError::Other(format!("canonicalize rules_dir: {e}")))?;

    let target = rules_dir.join(rel);

    // Create parent directories, then canonicalize the parent and re-check containment
    // to catch symlink-based escapes created after our lexical check.
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| CairnError::Other(format!("create parent dirs: {e}")))?;
        let canon_parent = parent
            .canonicalize()
            .map_err(|e| CairnError::Other(format!("canonicalize parent: {e}")))?;
        if !canon_parent.starts_with(&rules_dir) {
            return Err(CairnError::Other(format!(
                "path traversal via symlink: {} escapes {}",
                canon_parent.display(),
                rules_dir.display()
            )));
        }
    }

    // XOR-encode the rule bytes.
    let encoded = codec::xor(rule_bytes);

    // Write encoded bytes to disk.
    std::fs::write(&target, &encoded).map_err(|e| {
        CairnError::Other(format!("write encoded rule to {}: {e}", target.display()))
    })?;

    Ok(())
}

/// Write the PROVENANCE file to the rules directory.
///
/// Writes `rules_dir/PROVENANCE` with the provenance metadata in a format
/// matching fetch-and-encode.sh output.
pub fn write_provenance(rules_dir: &Path, provenance: &Provenance) -> Result<()> {
    let provenance_path = rules_dir.join("PROVENANCE");
    let content = provenance.to_file_content();
    std::fs::write(&provenance_path, content)
        .map_err(|e| CairnError::Other(format!("write PROVENANCE: {e}")))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provenance_formats_correctly() {
        let p = Provenance {
            pin: "98781da19cf60c48ce6e7f2d3ad11c9ba389191a".to_string(),
            source: "https://github.com/SigmaHQ/sigma".to_string(),
            fetched_at: "2026-06-25T12:34:56Z".to_string(),
        };
        let content = p.to_file_content();
        assert!(content.contains("pin = 98781da19cf60c48ce6e7f2d3ad11c9ba389191a"));
        assert!(content.contains("source = https://github.com/SigmaHQ/sigma"));
        assert!(content.contains("fetched_at = 2026-06-25T12:34:56Z"));
    }

    #[test]
    fn write_encoded_rule_encodes_and_writes() {
        let dir = std::env::temp_dir().join("cairn_encode_test");
        std::fs::create_dir_all(&dir).unwrap();

        let original = b"title: Test\nauthor: Alice\ndetection:\n";
        let result = write_encoded_rule_to_dir(&dir, original, "test/rule.yml");
        assert!(result.is_ok());

        let written = std::fs::read(dir.join("test/rule.yml")).unwrap();
        let decoded = codec::xor(&written);
        assert_eq!(decoded, original);
    }

    #[test]
    fn write_provenance_creates_file() {
        let dir = std::env::temp_dir().join("cairn_provenance_test");
        std::fs::create_dir_all(&dir).unwrap();

        let p = Provenance {
            pin: "abcd1234".to_string(),
            source: "https://example.com".to_string(),
            fetched_at: "2026-06-25T00:00:00Z".to_string(),
        };
        let result = write_provenance(&dir, &p);
        assert!(result.is_ok());

        let content = std::fs::read_to_string(dir.join("PROVENANCE")).unwrap();
        assert!(content.contains("pin = abcd1234"));
    }

    #[test]
    fn path_traversal_blocked() {
        let dir = std::env::temp_dir().join("cairn_traverse_test");
        std::fs::create_dir_all(&dir).unwrap();

        // `..` components must be rejected before any filesystem access.
        let result = write_encoded_rule_to_dir(&dir, b"test", "../../../etc/passwd");
        assert!(result.is_err(), "path traversal must be rejected");
        let msg = format!("{:?}", result.unwrap_err());
        assert!(
            msg.contains("unsafe rule path"),
            "error must mention 'unsafe rule path': {msg}"
        );
    }

    #[test]
    fn path_traversal_absolute_blocked() {
        let dir = std::env::temp_dir().join("cairn_traverse_abs_test");
        std::fs::create_dir_all(&dir).unwrap();

        let result = write_encoded_rule_to_dir(&dir, b"test", "/etc/passwd");
        assert!(result.is_err(), "absolute path must be rejected");
    }
}
